version: "3"

services:

  runtime-setup:
    image: swift-nio-email:18.04-5.2
    build:
      args:
        base_image: "swiftlang/swift:nightly-5.2-xenial"

  test:
    image: swift-nio-email:18.04-5.2

  shell:
    image: swift-nio-email:18.04-5.2
