version: "3"

services:

  runtime-setup:
    image: swift-nio-imap:20.04-5.7
    build:
      args:
        ubuntu_version: "focal"
        swift_version: "5.7"

  test:
    image: swift-nio-imap:20.04-5.7

  shell:
    image: swift-nio-imap:20.04-5.7
    
  performance-test:
    image: swift-nio-imap:20.04-5.7

  soundness:
    image: swift-nio-imap:20.04-5.7
