//===----------------------------------------------------------------------===//
//
// This source file is part of the SwiftNIO open source project
//
// Copyright (c) 2020 Apple Inc. and the SwiftNIO project authors
// Licensed under Apache License v2.0
//
// See LICENSE.txt for license information
// See CONTRIBUTORS.txt for the list of SwiftNIO project authors
//
// SPDX-License-Identifier: Apache-2.0
//
//===----------------------------------------------------------------------===//

import struct NIO.ByteBuffer

/// A hexadecimal-encoded URLAUTH verification token for IMAP URL authorization.
///
/// In URLAUTH-authorized URLs (RFC 4467), the authorization token is an ASCII-encoded
/// hexadecimal string that proves authorization for the URL. This token is generated by
/// the IMAP server using a server-selected algorithm (typically HMAC-SHA1 or similar) with
/// a mailbox access key as input. The token must be at least 128 bits (32 hexadecimal digits).
///
/// The token appears in the final component of the URLAUTH extension:
/// `;URLAUTH=<access>:<mechanism>:<token>`
///
/// Wraps the hexadecimal-encoded token string for use in URLAUTH verification
/// structures (via ``AuthenticatedURLVerifier``).
///
/// ### Example
///
/// In a GENURLAUTH response, the server generates and returns a URLAUTH-authorized URL
/// with the verification token included:
/// ```
/// C: a001 GENURLAUTH "imap://user@example.com/INBOX/;uid=20;urlauth=anonymous" INTERNAL
/// S: * GENURLAUTH "imap://user@example.com/INBOX/;uid=20;urlauth=anonymous:internal:91354a473744909de610943775f92038"
/// ```
///
/// The final hexadecimal string `91354a473744909de610943775f92038` is the token,
/// wrapped as:
/// ```
/// EncodedAuthenticatedURL(data: "91354a473744909de610943775f92038")
/// ```
///
/// When a client later uses this URL with URLFETCH, the server re-calculates the token
/// to verify authorization before returning the message data.
///
/// ## Related types
///
/// See ``URLAuthenticationMechanism`` for the mechanism specification, ``AuthenticatedURLVerifier``
/// for the complete mechanism and token pair, and ``AuthenticatedURL`` for the full
/// authorization structure.
///
/// - SeeAlso: [RFC 4467 Section 2.5](https://datatracker.ietf.org/doc/html/rfc4467#section-2.5) - Authorization Token
/// - SeeAlso: [RFC 4467 Section 5](https://datatracker.ietf.org/doc/html/rfc4467#section-5) - Generation of URLAUTH-Authorized URLs
/// - SeeAlso: [RFC 4467 Section 6](https://datatracker.ietf.org/doc/html/rfc4467#section-6) - Validation of URLAUTH-authorized URLs
public struct EncodedAuthenticatedURL: Hashable, Sendable {
    /// The hexadecimal-encoded authorization token string.
    ///
    /// An ASCII-encoded hexadecimal representation of the token bytes. The RFC 4467
    /// specification recommends using hexadecimal instead of Base64 to avoid URL-problematic
    /// padding characters.
    public var data: String

    /// Creates a new hexadecimal-encoded URLAUTH verification token.
    /// - parameter data: The hexadecimal-encoded token string.
    public init(data: String) {
        self.data = data
    }
}

extension EncodeBuffer {
    @discardableResult mutating func writeEncodedAuthenticationURL(_ data: EncodedAuthenticatedURL) -> Int {
        self.writeString(data.data)
    }
}
